<a href="https://colab.research.google.com/github/leman-cap13/DL_projects/blob/main/Deeplearning_Torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PyTorch Fundamentals

In [1]:
import torch

In [2]:
X= torch.tensor([[1.0, 2.0, 4.0],[3.0, 5.0, 6.0]])

In [3]:
X.shape

torch.Size([2, 3])

In [4]:
X.dtype

torch.float32

In [5]:
X.mean()

tensor(3.5000)

In [6]:
torch.mean(X)

tensor(3.5000)

In [7]:
X.max()

tensor(6.)

In [8]:
X

tensor([[1., 2., 4.],
        [3., 5., 6.]])

In [9]:
X.max(dim=0)

torch.return_types.max(
values=tensor([3., 5., 6.]),
indices=tensor([1, 1, 1]))

In [10]:
X.min()

tensor(1.)

In [11]:
X.exp()

tensor([[  2.7183,   7.3891,  54.5981],
        [ 20.0855, 148.4132, 403.4288]])

In [12]:
X[0,1]

tensor(2.)

In [13]:
X[:,1]

tensor([2., 5.])

In [14]:
X[:,1]=-99
X

tensor([[  1., -99.,   4.],
        [  3., -99.,   6.]])

In [15]:
X.abs()

tensor([[ 1., 99.,  4.],
        [ 3., 99.,  6.]])

In [16]:
X

tensor([[  1., -99.,   4.],
        [  3., -99.,   6.]])

In [17]:
X.abs_()

tensor([[ 1., 99.,  4.],
        [ 3., 99.,  6.]])

In [18]:
X

tensor([[ 1., 99.,  4.],
        [ 3., 99.,  6.]])

In [19]:
X=X.numpy()
X

array([[ 1., 99.,  4.],
       [ 3., 99.,  6.]], dtype=float32)

In [20]:
import numpy as np

In [21]:
torch.tensor(np.array([[1.0, 2.0, 4.0],[3.0, 5.0, 6.0]]))

tensor([[1., 2., 4.],
        [3., 5., 6.]], dtype=torch.float64)

In [22]:
M=torch.tensor(np.array([[1.0, 2.0, 4.0],[3.0, 5.0, 6.0]], dtype=np.float32))
M


tensor([[1., 2., 4.],
        [3., 5., 6.]])

In [23]:
M.dtype

torch.float32

In [24]:
N=torch.FloatTensor(np.array([[1.0, 2.0, 4.0],[3.0, 5.0, 6.0]]))
N

tensor([[1., 2., 4.],
        [3., 5., 6.]])

In [25]:
N.dtype

torch.float32

In [26]:
torch.tensor([[1.0, 2.0, 4.0],[3.0, 5.0, 6.0]])

tensor([[1., 2., 4.],
        [3., 5., 6.]])

In [27]:
M=torch.tensor(5.0, requires_grad=True)
y=M**2
y

tensor(25., grad_fn=<PowBackward0>)

In [28]:
y.backward()

In [29]:
M.grad

tensor(10.)

In [30]:
learning_rate=0.1

In [31]:
M.grad

tensor(10.)

In [32]:
with torch.no_grad():
  M-=learning_rate * M.grad
M

tensor(4., requires_grad=True)

In [33]:
X_detach=M.detach()

In [34]:
# torch.zero_grad()

In [35]:
if torch.cuda.is_available():
  device='cuda'
elif torch.backends.mps.is_available():
  device='mps'
else:
  device='cpu'

In [36]:
X= torch.tensor([[1.0, 2.0, 4.0],[3.0, 5.0, 6.0]])

In [37]:
X=X.to(device)

In [38]:
X.device

device(type='cpu')

In [39]:
from sklearn.datasets import fetch_california_housing
from sklearn. model_selection import train_test_split

In [40]:
X, y=fetch_california_housing(return_X_y=True)

In [41]:
X_train_full, X_test, y_train_full, y_test=train_test_split(X,y, test_size=0.2, random_state=42)

In [42]:
X_train, X_valid, y_train,y_valid= train_test_split(X_train_full, y_train_full, test_size=0.2, random_state=42)

In [43]:
X_train.shape

(13209, 8)

In [44]:
X_train.dtype

dtype('float64')

In [45]:
X_train = torch.tensor(X_train, dtype=torch.float32).to(device)
X_test=torch.tensor(X_test, dtype=torch.float32).to(device)
X_valid=torch.tensor(X_valid, dtype=torch.float32).to(device)

In [46]:
X_train.dtype

torch.float32

In [47]:
means=X_train.mean(dim=0, keepdims=True)
stds=X_train.std(dim=0, keepdims=True)
X_train= (X_train - means)/ stds
X_test= (X_test - means)/ stds
X_valid= (X_valid - means)/ stds

In [48]:
X_train.dtype

torch.float32

In [49]:
X_train.shape

torch.Size([13209, 8])

In [50]:
y_train.dtype

dtype('float64')

In [51]:
y_train.shape

(13209,)

In [52]:
A=y_train.reshape(-1,1)
A.shape

(13209, 1)

In [53]:
y_train=torch.FloatTensor(y_train).reshape(-1,1).to(device)
y_valid=torch.FloatTensor(y_valid).reshape(-1,1).to(device)
y_test=torch.FloatTensor(y_test).reshape(-1,1).to(device)

In [54]:
y_train.shape

torch.Size([13209, 1])

In [55]:
X_train.shape[1]

8

In [56]:
torch.manual_seed(42)
n_feature=X_train.shape[1]
w=torch.randn((n_feature,1), requires_grad=True, device=device)
b=torch.tensor(0., requires_grad=True, device=device)

In [57]:
n_epochs=20
learning_rate=0.4
for epoch in range(n_epochs):
  y_pred=X_train @ w + b
  loss=torch.mean((y_pred-y_train) **2)
  loss.backward()
  with torch.no_grad():
    w -= learning_rate * w.grad
    b -= learning_rate * b.grad
    w.grad.zero_()
    b.grad.zero_()
  print(f"Epoch{epoch + 1}/ {n_epochs}, loss: { loss. item()}")

Epoch1/ 20, loss: 16.0495548248291
Epoch2/ 20, loss: 4.7265167236328125
Epoch3/ 20, loss: 2.14831280708313
Epoch4/ 20, loss: 1.26175057888031
Epoch5/ 20, loss: 0.922484278678894
Epoch6/ 20, loss: 0.7815980911254883
Epoch7/ 20, loss: 0.7158308029174805
Epoch8/ 20, loss: 0.6797962784767151
Epoch9/ 20, loss: 0.6563625931739807
Epoch10/ 20, loss: 0.6388929486274719
Epoch11/ 20, loss: 0.624715268611908
Epoch12/ 20, loss: 0.6126787066459656
Epoch13/ 20, loss: 0.6022298336029053
Epoch14/ 20, loss: 0.5930586457252502
Epoch15/ 20, loss: 0.584962010383606
Epoch16/ 20, loss: 0.577788770198822
Epoch17/ 20, loss: 0.5714176297187805
Epoch18/ 20, loss: 0.5657473802566528
Epoch19/ 20, loss: 0.5606915950775146
Epoch20/ 20, loss: 0.5561758875846863


In [58]:
import torch.nn as nn
torch.manual_seed(42)

In [59]:
model=nn.Linear(in_features=n_feature, out_features=1)
model=model.to(device)

In [60]:
model.bias

Parameter containing:
tensor([0.3117], requires_grad=True)

In [61]:
model.weight

Parameter containing:
tensor([[ 0.2703,  0.2935, -0.0828,  0.3248, -0.0775,  0.0713, -0.1721,  0.2076]],
       requires_grad=True)

In [62]:
for param in model.parameters():
  print(param)

Parameter containing:
tensor([[ 0.2703,  0.2935, -0.0828,  0.3248, -0.0775,  0.0713, -0.1721,  0.2076]],
       requires_grad=True)
Parameter containing:
tensor([0.3117], requires_grad=True)


In [63]:
optimizer=torch.optim.SGD(model.parameters(), lr=learning_rate)

In [64]:
criterion=nn.MSELoss()
criterion

MSELoss()

In [65]:
def train(model, optimizer, criterion, X_train, y_train, n_epochs):
  for epoch in range(n_epochs):
    y_pred=model(X_train)
    loss=criterion(y_pred, y_train)
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()
    print(f"epoch{epoch+1}/ { n_epochs}, loss: { loss. item()}")


In [66]:
train(
    model=model,
    optimizer=optimizer,
    criterion=criterion,
    X_train=X_train,
    y_train=y_train,
    n_epochs=20
)

epoch1/ 20, loss: 4.270204544067383
epoch2/ 20, loss: 0.7620968222618103
epoch3/ 20, loss: 0.6113184094429016
epoch4/ 20, loss: 0.5919578075408936
epoch5/ 20, loss: 0.581246018409729
epoch6/ 20, loss: 0.5727843046188354
epoch7/ 20, loss: 0.5656700730323792
epoch8/ 20, loss: 0.5595568418502808
epoch9/ 20, loss: 0.5542512536048889
epoch10/ 20, loss: 0.5496227145195007
epoch11/ 20, loss: 0.5455722808837891
epoch12/ 20, loss: 0.5420194864273071
epoch13/ 20, loss: 0.5388972759246826
epoch14/ 20, loss: 0.5361485481262207
epoch15/ 20, loss: 0.5337244868278503
epoch16/ 20, loss: 0.5315830111503601
epoch17/ 20, loss: 0.5296878814697266
epoch18/ 20, loss: 0.5280079245567322
epoch19/ 20, loss: 0.5265161991119385
epoch20/ 20, loss: 0.5251892805099487


#Implementing a Regression MLP

In [67]:
torch.manual_seed(42)
model=nn.Sequential(
    nn.Linear(in_features=n_feature, out_features=50),
    nn.ReLU(),
    nn.Linear(in_features=50, out_features=40),
    nn.ReLU(),
    nn.Linear(in_features=40, out_features=1)
)

model=model.to(device)

In [68]:
learning_rate=0.1

In [69]:
optimizer=torch.optim.SGD(model.parameters(), lr=learning_rate)

In [70]:
criterian=nn.MSELoss()

In [71]:
train(
    model=model,
    optimizer=optimizer,
    criterion=criterian,
    X_train=X_train,
    y_train=y_train,
    n_epochs=20
)

epoch1/ 20, loss: 4.971917629241943
epoch2/ 20, loss: 2.0490026473999023
epoch3/ 20, loss: 1.005563735961914
epoch4/ 20, loss: 0.8661571741104126
epoch5/ 20, loss: 0.7838791608810425
epoch6/ 20, loss: 0.732201874256134
epoch7/ 20, loss: 0.6987428665161133
epoch8/ 20, loss: 0.6764352321624756
epoch9/ 20, loss: 0.6608064770698547
epoch10/ 20, loss: 0.6491540670394897
epoch11/ 20, loss: 0.6398535370826721
epoch12/ 20, loss: 0.6319313049316406
epoch13/ 20, loss: 0.6248724460601807
epoch14/ 20, loss: 0.6183494925498962
epoch15/ 20, loss: 0.6122236847877502
epoch16/ 20, loss: 0.6063849329948425
epoch17/ 20, loss: 0.6007853150367737
epoch18/ 20, loss: 0.5953795313835144
epoch19/ 20, loss: 0.5901413559913635
epoch20/ 20, loss: 0.5850571393966675


In [72]:
#Dataloader

In [73]:
from torch.utils.data import TensorDataset, DataLoader

In [74]:
X_train.dtype

torch.float32

In [75]:
X_train

tensor([[ 0.4434, -0.1245,  0.5205,  ...,  0.0517,  1.1028, -0.6915],
        [ 0.0032, -1.0777, -0.1708,  ..., -0.0552, -0.7249,  0.8544],
        [-0.5218, -0.2039, -0.0612,  ..., -0.0170, -0.8843,  0.8644],
        ...,
        [ 0.0611, -0.8394,  0.0611,  ...,  0.0311, -1.3623,  1.2932],
        [ 0.3398, -0.9982, -0.4748,  ..., -0.1376, -0.8468,  0.8544],
        [ 0.1752,  0.5110, -0.4947,  ..., -0.0077, -0.8140,  0.6300]])

In [76]:
train_dataset=TensorDataset(X_train, y_train)   # __len__(self),    __getitem__(self, index)

In [77]:
train_dataset

In [78]:
train_dataset[0]

(tensor([ 0.4434, -0.1245,  0.5205,  0.0576, -0.4871,  0.0517,  1.1028, -0.6915]),
 tensor([1.7690]))

In [79]:
X_train[0], y_train[0]

(tensor([ 0.4434, -0.1245,  0.5205,  0.0576, -0.4871,  0.0517,  1.1028, -0.6915]),
 tensor([1.7690]))

In [80]:
len(train_dataset)

13209

In [81]:
train_loader= DataLoader(
    train_dataset,
    batch_size=32,
    shuffle=True

)

In [82]:
def train(model, optimizer, criterion, train_loader, n_epochs):
  model.train()
  for epoch in range(n_epochs):
    total_loss=0.
    for X_batch, y_batch in train_loader:
      X_batch = X_batch.to(device)
      y_batch= y_batch.to(device)

      y_pred= model(X_batch)
      loss=criterion(y_pred, y_batch)
      total_loss += loss.item()

      loss.backward()
      optimizer.step()
      optimizer.zero_grad()
    mean_loss = total_loss / len( train_loader)
    print(f"epoch { epoch +1}/ {n_epochs}, loss { mean_loss:.4}")

In [83]:
train(
    model=model,
    optimizer=optimizer,
    criterion=criterian,
    train_loader=train_loader,
    n_epochs=20
)

epoch 1/ 20, loss 0.5107
epoch 2/ 20, loss 0.4186
epoch 3/ 20, loss 0.4104
epoch 4/ 20, loss 0.3853
epoch 5/ 20, loss 0.3701
epoch 6/ 20, loss 0.3519
epoch 7/ 20, loss 0.3417
epoch 8/ 20, loss 0.3414
epoch 9/ 20, loss nan
epoch 10/ 20, loss nan
epoch 11/ 20, loss nan
epoch 12/ 20, loss nan
epoch 13/ 20, loss nan
epoch 14/ 20, loss nan
epoch 15/ 20, loss nan
epoch 16/ 20, loss nan
epoch 17/ 20, loss nan
epoch 18/ 20, loss nan
epoch 19/ 20, loss nan
epoch 20/ 20, loss nan


In [84]:
 # eval

In [85]:
valid_dataset=TensorDataset(X_valid, y_valid)

In [86]:
X_valid

tensor([[-0.1754,  0.5110,  0.5302,  ..., -0.0115,  0.5123, -0.1330],
        [-0.8976, -0.4422, -0.5348,  ..., -0.0454,  2.5181, -2.2823],
        [ 0.1789, -1.1571, -0.7095,  ..., -0.1528, -0.9264,  0.8295],
        ...,
        [-0.1468, -0.6011, -0.3962,  ..., -0.0112, -1.0202,  0.9392],
        [-0.1291, -0.2834, -0.0431,  ..., -0.1370, -1.3341,  1.2484],
        [-0.1200, -0.7599, -0.5079,  ..., -0.0561, -0.8561,  0.8095]])

In [87]:
valid_loader=DataLoader(
    valid_dataset,
    batch_size=32,
    shuffle=False
)

In [88]:
def evaluate(model, data_loader, metric_fn, aggregate_fn=torch.mean):
  model.eval()
  metrics=[]
  with torch.no_grad():
    for X_batch, y_batch in data_loader:
      X_batch, y_batch = X_batch.to(device), y_batch.to(device)
      y_pred=model(X_batch)
      metric=metric_fn(y_pred, y_batch)
      metrics.append(metric)    # [tensor(3), tensor(4), tensor(5)]  ----> tensor(3,4,5)
  return aggregate_fn(torch.stack(metrics))

In [89]:
valid_mse=evaluate(
    model=model,
    data_loader=valid_loader,
    metric_fn=criterion
)

In [90]:
valid_mse

tensor(nan)

In [91]:
def rmse(y_pred, y_true):
  return ((y_pred- y_true)**2).mean().sqrt()

In [92]:
evaluate(
    model=model,
    data_loader=valid_loader,
    metric_fn=rmse
)

tensor(nan)

In [93]:
valid_mse.sqrt()

tensor(nan)

In [94]:
evaluate(
    model=model,
    data_loader=valid_loader,
    metric_fn=criterion,
    aggregate_fn = lambda metrics : torch.sqrt(torch.mean(metrics))
)

tensor(nan)

In [95]:
! pip install torchmetrics

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 37.0 MB/s eta 0:00:00


In [96]:
import torchmetrics

In [97]:
def tm_evaluate(model, data_loader, metric):
  model.eval()
  metric.reset()
  with torch.no_grad():
    for X_batch, y_batch in data_loader:
      X_batch, y_batch = X_batch.to(device), y_batch.to(device)
      y_pred=model(X_batch)
      metric.update(y_pred, y_batch)
  return metric.compute()


In [98]:
rmse=torchmetrics.MeanSquaredError(squared=False).to(device)

In [99]:
tm_evaluate(
    model=model,
    data_loader=valid_loader,
    metric=rmse
)

tensor(nan)

#Load_diabetes

In [ ]:
from sklearn.datasets import load_diabetes

data = load_diabetes()
X = data.data
y = data.target

print(X.shape)
print(y.shape)

(442, 10)
(442,)


In [ ]:
from sklearn.model_selection import train_test_split

X_train_full, X_test, y_train_full, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

X_train, X_valid, y_train, y_valid = train_test_split(
    X_train_full, y_train_full, test_size=0.2, random_state=42
)

print(X_train.shape, X_valid.shape, X_test.shape)

(282, 10) (71, 10) (89, 10)


In [ ]:
from sklearn.preprocessing import StandardScaler

scaler_X = StandardScaler()
X_train = scaler_X.fit_transform(X_train)
X_valid = scaler_X.transform(X_valid)
X_test = scaler_X.transform(X_test)

In [ ]:
import torch

X_train = torch.tensor(X_train, dtype=torch.float32)
X_valid = torch.tensor(X_valid, dtype=torch.float32)
X_test  = torch.tensor(X_test, dtype=torch.float32)

y_train = torch.tensor(y_train.reshape(-1, 1), dtype=torch.float32)
y_valid = torch.tensor(y_valid.reshape(-1, 1), dtype=torch.float32)
y_test  = torch.tensor(y_test.reshape(-1, 1), dtype=torch.float32)

print(X_train.shape, y_train.shape)

torch.Size([282, 10]) torch.Size([282, 1])


In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cpu


In [ ]:
from torch.utils.data import TensorDataset, DataLoader

train_dataset = TensorDataset(X_train, y_train)
valid_dataset = TensorDataset(X_valid, y_valid)
test_dataset  = TensorDataset(X_test, y_test)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
valid_loader = DataLoader(valid_dataset, batch_size=32, shuffle=False)
test_loader  = DataLoader(test_dataset, batch_size=32, shuffle=False)

In [ ]:
import torch.nn as nn

n_feature = X_train.shape[1]

torch.manual_seed(42)
model = nn.Sequential(
    nn.Linear(n_feature, 50),
    nn.ReLU(),
    nn.Linear(50, 40),
    nn.ReLU(),
    nn.Linear(40, 1)
).to(device)

print(model)

Sequential(
  (0): Linear(in_features=10, out_features=50, bias=True)
  (1): ReLU()
  (2): Linear(in_features=50, out_features=40, bias=True)
  (3): ReLU()
  (4): Linear(in_features=40, out_features=1, bias=True)
)


In [ ]:
learning_rate = 0.001
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
criterion = nn.MSELoss()

In [ ]:
def mb_train(model, optimizer, criterion, train_loader, valid_loader, n_epochs):
    train_losses = []
    valid_losses = []

    for epoch in range(n_epochs):
        model.train()
        total_train_loss = 0.0

        for X_batch, y_batch in train_loader:
            X_batch = X_batch.to(device)
            y_batch = y_batch.to(device)

            optimizer.zero_grad()
            y_pred = model(X_batch)
            loss = criterion(y_pred, y_batch)
            loss.backward()
            optimizer.step()

            total_train_loss += loss.item()

        mean_train_loss = total_train_loss / len(train_loader)
        train_losses.append(mean_train_loss)

        model.eval()
        total_valid_loss = 0.0
        with torch.no_grad():
            for X_batch, y_batch in valid_loader:
                X_batch = X_batch.to(device)
                y_batch = y_batch.to(device)

                y_pred = model(X_batch)
                loss = criterion(y_pred, y_batch)
                total_valid_loss += loss.item()

        mean_valid_loss = total_valid_loss / len(valid_loader)
        valid_losses.append(mean_valid_loss)

        print(f"Epoch {epoch+1}/{n_epochs} | train_loss={mean_train_loss:.4f} | valid_loss={mean_valid_loss:.4f}")

    return train_losses, valid_losses

In [ ]:
train_losses, valid_losses = mb_train(
    model=model,
    optimizer=optimizer,
    criterion=criterion,
    train_loader=train_loader,
    valid_loader=valid_loader,
    n_epochs=50
)

Epoch 1/50 | train_loss=0.2897 | valid_loss=0.4801
Epoch 2/50 | train_loss=0.2850 | valid_loss=0.4801
Epoch 3/50 | train_loss=0.2851 | valid_loss=0.4802
Epoch 4/50 | train_loss=0.2844 | valid_loss=0.4805
Epoch 5/50 | train_loss=0.2857 | valid_loss=0.4806
Epoch 6/50 | train_loss=0.2863 | valid_loss=0.4804
Epoch 7/50 | train_loss=0.2843 | valid_loss=0.4803
Epoch 8/50 | train_loss=0.2849 | valid_loss=0.4802
Epoch 9/50 | train_loss=0.2850 | valid_loss=0.4802
Epoch 10/50 | train_loss=0.2835 | valid_loss=0.4802
Epoch 11/50 | train_loss=0.2864 | valid_loss=0.4802
Epoch 12/50 | train_loss=0.2853 | valid_loss=0.4801
Epoch 13/50 | train_loss=0.2845 | valid_loss=0.4802
Epoch 14/50 | train_loss=0.2841 | valid_loss=0.4802
Epoch 15/50 | train_loss=0.2831 | valid_loss=0.4803
Epoch 16/50 | train_loss=0.2821 | valid_loss=0.4803
Epoch 17/50 | train_loss=0.2849 | valid_loss=0.4803
Epoch 18/50 | train_loss=0.2845 | valid_loss=0.4804
Epoch 19/50 | train_loss=0.2832 | valid_loss=0.4806
Epoch 20/50 | train_l

#Building Nonsequential Models Using Custom Modules


In [107]:
n_features = X_train.shape[1]

In [108]:
class WideAndDeep(nn.Module):
  def __init__(self, n_features):
    super().__init__()
    self.deep_stack=nn.Sequential(
        nn.Linear(n_features, 50),
        nn.ReLU(),
        nn.Linear(50,40),
        nn.ReLU()
    )
    self.output_layer=nn.Linear(40+ n_features, 1)

  def forward(self, X):
    deep_output=self.deep_stack(X)
    wide_and_deep= torch.concat([X, deep_output], dim=1)
    return self.output_layer(wide_and_deep)


In [109]:
torch.manual_seed(42)
model=WideAndDeep(n_features)
model=model.to(device)

In [110]:
learning_rate=0.002

In [111]:
optimizer=torch.optim.SGD(model.parameters(), lr=learning_rate)

In [112]:
criterion=nn.MSELoss()

In [113]:
train(
    model=model,
    optimizer=optimizer,
    criterion=criterion,
    train_loader=train_loader,
    n_epochs=20
)

epoch 1/ 20, loss 1.332
epoch 2/ 20, loss 0.6117
epoch 3/ 20, loss 0.5662
epoch 4/ 20, loss 0.5345
epoch 5/ 20, loss 0.5104
epoch 6/ 20, loss 0.4929
epoch 7/ 20, loss 0.4804
epoch 8/ 20, loss 0.4683
epoch 9/ 20, loss 0.4589
epoch 10/ 20, loss 0.4501
epoch 11/ 20, loss 0.4423
epoch 12/ 20, loss 0.4354
epoch 13/ 20, loss 0.4282
epoch 14/ 20, loss 0.4228
epoch 15/ 20, loss 0.4167
epoch 16/ 20, loss 0.4116
epoch 17/ 20, loss 0.4075
epoch 18/ 20, loss 0.4018
epoch 19/ 20, loss 0.3971
epoch 20/ 20, loss 0.3934


In [114]:
evaluate(
    model=model,
    data_loader=valid_loader,
    metric_fn=criterion,
    aggregate_fn = lambda metrics : torch.sqrt(torch.mean(metrics))
)

tensor(0.6518)

In [121]:
class WideAndDeep2(nn.Module):
    def __init__(self, n_features):
        super().__init__()

        n_wide_features = 5
        n_deep_features = n_features - 2

        self.deep_stack = nn.Sequential(
            nn.Linear(n_deep_features, 50),
            nn.ReLU(),
            nn.Linear(50, 40),
            nn.ReLU(),
        )

        self.output_layer = nn.Linear(40 + n_wide_features, 1)

    def forward(self, X):
        X_wide = X[:, :5]
        X_deep = X[:, 2:]

        deep_output = self.deep_stack(X_deep)
        wide_and_deep = torch.cat([X_wide, deep_output], dim=1)
        return self.output_layer(wide_and_deep)

In [122]:
torch.manual_seed(42)
model=WideAndDeep2(n_features)
model=model.to(device)

In [123]:
optimizer=torch.optim.SGD(model.parameters(), lr=learning_rate)

In [124]:
train(
    model=model,
    optimizer=optimizer,
    criterion=criterion,
    train_loader=train_loader,
    n_epochs=20
)

epoch 1/ 20, loss 1.384
epoch 2/ 20, loss 0.6061
epoch 3/ 20, loss 0.5504
epoch 4/ 20, loss 0.5176
epoch 5/ 20, loss 0.4971
epoch 6/ 20, loss 0.4822
epoch 7/ 20, loss 0.4706
epoch 8/ 20, loss 0.4619
epoch 9/ 20, loss 0.4547
epoch 10/ 20, loss 0.4486
epoch 11/ 20, loss 0.4426
epoch 12/ 20, loss 0.4383
epoch 13/ 20, loss 0.4341
epoch 14/ 20, loss 0.4307
epoch 15/ 20, loss 0.4277
epoch 16/ 20, loss 0.4244
epoch 17/ 20, loss 0.4227
epoch 18/ 20, loss 0.4199
epoch 19/ 20, loss 0.4176
epoch 20/ 20, loss 0.4159


In [125]:
evaluate(
    model=model,
    data_loader=valid_loader,
    metric_fn=criterion,
    aggregate_fn = lambda metrics : torch.sqrt(torch.mean(metrics))
)

tensor(0.6642)

In [128]:
list(model.children())

[Sequential(
   (0): Linear(in_features=6, out_features=50, bias=True)
   (1): ReLU()
   (2): Linear(in_features=50, out_features=40, bias=True)
   (3): ReLU()
 ),
 Linear(in_features=45, out_features=1, bias=True)]

In [129]:
list(model.named_children())

[('deep_stack',
  Sequential(
    (0): Linear(in_features=6, out_features=50, bias=True)
    (1): ReLU()
    (2): Linear(in_features=50, out_features=40, bias=True)
    (3): ReLU()
  )),
 ('output_layer', Linear(in_features=45, out_features=1, bias=True))]

In [130]:
# class BadModel(nn.Module):
#     def __init__(self):
#         super().__init__()
#         self.layers = [
#             nn.Linear(8, 16),
#             nn.ReLU(),
#             nn.Linear(16, 1)
#         ]


# # list olduguna gore PyTorch üçün bunlar rəsmi submodule kimi görünməyə bilər.
# list(model.children())----> çox güman boş və ya gözlədiyin kimi olmayacaq.
# model.parameters() ------># bu list içindəki layer-lərin weight-lərini tapmaya bilər.



# Əgər modelində dəyişən sayda layer varsa, onları adi list yox, nn.ModuleList içində saxlamalısan.


# class GoodModel(nn.Module):
#     def __init__(self):
#         super().__init__()
#         self.layers = nn.ModuleList([
#             nn.Linear(8, 16),
#             nn.ReLU(),
#             nn.Linear(16, 1)
#         ])


# bunları children(), parameters(), to(device) etc daxil ede bilir


# ModuleList ve Sequentialdən fərqi?

# nn.Sequential --->Layer-ləri avtomatik ardıcıl tətbiq edir.

# self.net = nn.Sequential(
#     nn.Linear(8, 16),
#     nn.ReLU(),
#     nn.Linear(16, 1)
# )

# Bu halda forward()-da sadəcə---> return self.net(X)


# nn.ModuleList

# Sadəcə module-ləri saxlayır. Avtomatik tətbiq etmir.

# self.layers = nn.ModuleList([
#     nn.Linear(8, 16),
#     nn.ReLU(),
#     nn.Linear(16, 1)
# ])

# Bu halda forward()-da özün loop yazmalısan:

# def forward(self, X):
#     for layer in self.layers:
#         X = layer(X)
#     return X


# Sequential = həm saxlayır, həm tətbiq edir
# ModuleList = yalnız düzgün saxlayır ama loop yazmalisan manual

In [133]:
#Building Models with Multiple Inputs

class WideAndDeep3(nn.Module):
    def __init__(self, n_features):
        super().__init__()

        n_wide_features = 5
        n_deep_features = n_features - 2

        self.deep_stack = nn.Sequential(
            nn.Linear(n_deep_features, 50),
            nn.ReLU(),
            nn.Linear(50, 40),
            nn.ReLU(),
        )

        self.output_layer = nn.Linear(40 + n_wide_features, 1)

    def forward(self, X_wide, X_deep)  :
      deep_output= self.deep_stack(X_deep)
      wide_and_deep= torch.concat([X_wide, deep_output], dim=1)
      return self.output_layer(wide_and_deep)


In [134]:
torch.manual_seed(42)
model=WideAndDeep3(n_features)
model=model.to(device)

In [135]:
optimizer=torch.optim.SGD(model.parameters(), lr=learning_rate)

In [136]:
train_data_wd = TensorDataset(X_train[:, :5], X_train[:, 2:], y_train)

train_loader_wd = DataLoader(
    train_data_wd,
    batch_size=32,
    shuffle=True)

valid_data_wd = TensorDataset(X_valid[:, :5], X_valid[:, 2:], y_valid)

valid_loader_wd = DataLoader(
    valid_data_wd,
    batch_size=32,
    shuffle=False)

In [137]:
def train(model, optimizer, criterion, data_loader, n_epochs):
  model.train()
  for epoch in range(n_epochs):
    total_loss=0.

    for X_batch_wide, X_batch_deep, y_batch in data_loader:
        X_batch_wide = X_batch_wide.to(device)
        X_batch_deep = X_batch_deep.to(device)
        y_batch = y_batch.to(device)
        y_pred = model(X_batch_wide, X_batch_deep)

        loss=criterion(y_pred, y_batch)
        total_loss += loss.item()

        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
    mean_loss = total_loss / len( data_loader)
    print(f"epoch { epoch +1}/ {n_epochs}, loss { mean_loss:.4}")

In [138]:
train(
    model=model,
    optimizer=optimizer,
    criterion=criterion,
    data_loader=train_loader_wd,
    n_epochs=20
)

epoch 1/ 20, loss 1.384
epoch 2/ 20, loss 0.6061
epoch 3/ 20, loss 0.5504
epoch 4/ 20, loss 0.5176
epoch 5/ 20, loss 0.4971
epoch 6/ 20, loss 0.4822
epoch 7/ 20, loss 0.4706
epoch 8/ 20, loss 0.4619
epoch 9/ 20, loss 0.4547
epoch 10/ 20, loss 0.4486
epoch 11/ 20, loss 0.4426
epoch 12/ 20, loss 0.4383
epoch 13/ 20, loss 0.4341
epoch 14/ 20, loss 0.4307
epoch 15/ 20, loss 0.4277
epoch 16/ 20, loss 0.4244
epoch 17/ 20, loss 0.4227
epoch 18/ 20, loss 0.4199
epoch 19/ 20, loss 0.4176
epoch 20/ 20, loss 0.4159


In [139]:
def evaluate(model, data_loader, metric_fn, aggregate_fn=torch.mean):
    model.eval()
    metrics = []

    with torch.no_grad():
        for X_batch_wide, X_batch_deep, y_batch in data_loader:
            X_batch_wide = X_batch_wide.to(device)
            X_batch_deep = X_batch_deep.to(device)
            y_batch = y_batch.to(device)

            y_pred = model(X_batch_wide, X_batch_deep)
            metric = metric_fn(y_pred, y_batch)
            metrics.append(metric)

    return aggregate_fn(torch.stack(metrics))

In [140]:
evaluate(
    model=model,
    data_loader=valid_loader_wd,
    metric_fn=criterion,
    aggregate_fn = lambda metrics : torch.sqrt(torch.mean(metrics))
)

tensor(0.6642)

In [141]:
from torch.utils.data import Dataset

In [151]:
class WideAndDeep3(nn.Module):
    def __init__(self, n_wide_features, n_deep_features):
        super().__init__()

        self.deep_stack = nn.Sequential(
            nn.Linear(n_deep_features, 50),
            nn.ReLU(),
            nn.Linear(50, 40),
            nn.ReLU(),
        )

        self.output_layer = nn.Linear(40 + n_wide_features, 1)

    def forward(self, X_wide, X_deep):
        deep_output = self.deep_stack(X_deep)
        wide_and_deep = torch.cat([X_wide, deep_output], dim=1)
        return self.output_layer(wide_and_deep)

In [143]:
class WideAndDeepDataset(Dataset):
    def __init__(self, X_wide, X_deep, y):
        self.X_wide = X_wide
        self.X_deep = X_deep
        self.y = y

    def __len__(self):
        return len(self.y)

    def __getitem__(self, idx):
        inputs = {
            "X_wide": self.X_wide[idx],
            "X_deep": self.X_deep[idx]
        }
        return inputs, self.y[idx]


In [144]:
train_dataset=WideAndDeepDataset(
    X_wide=X_train[:, :5],
    X_deep=X_train[:, 2:],
    y=y_train
)

valid_dataset=WideAndDeepDataset(
    X_wide=X_valid[:, :5],
    X_deep=X_valid[:, 2:],
    y=y_valid
)

In [146]:
train_loader = DataLoader(
    train_dataset,
    batch_size=32,
    shuffle=True
)

valid_loader = DataLoader(
    valid_dataset,
    batch_size=32,
    shuffle=False
)

In [149]:
X_train[:, 2:].shape[1]

6

In [152]:
torch.manual_seed(42)

model = WideAndDeep3(
    n_wide_features=X_train[:, :5].shape[1],
    n_deep_features=X_train[:, 2:].shape[1]
).to(device)

In [153]:
learning_rate = 0.002
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
criterion = nn.MSELoss()

In [154]:
def train(model, optimizer, criterion, data_loader, n_epochs):
    model.train()

    for epoch in range(n_epochs):
        total_loss = 0.0

        for inputs, y_batch in data_loader:
            inputs = {name: X.to(device) for name, X in inputs.items()}
            y_batch = y_batch.to(device)

            optimizer.zero_grad()

            y_pred = model(**inputs)
            loss = criterion(y_pred, y_batch)

            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        mean_loss = total_loss / len(data_loader)
        print(f"epoch {epoch + 1}/{n_epochs}, loss {mean_loss:.4f}")

In [155]:
train(
    model=model,
    optimizer=optimizer,
    criterion=criterion,
    data_loader=train_loader,
    n_epochs=20
)

epoch 1/20, loss 1.3836
epoch 2/20, loss 0.6061
epoch 3/20, loss 0.5504
epoch 4/20, loss 0.5176
epoch 5/20, loss 0.4971
epoch 6/20, loss 0.4822
epoch 7/20, loss 0.4706
epoch 8/20, loss 0.4619
epoch 9/20, loss 0.4547
epoch 10/20, loss 0.4486
epoch 11/20, loss 0.4426
epoch 12/20, loss 0.4383
epoch 13/20, loss 0.4341
epoch 14/20, loss 0.4307
epoch 15/20, loss 0.4277
epoch 16/20, loss 0.4244
epoch 17/20, loss 0.4227
epoch 18/20, loss 0.4199
epoch 19/20, loss 0.4176
epoch 20/20, loss 0.4159


In [156]:
def evaluate(model, data_loader, metric_fn, aggregate_fn=torch.mean):
    model.eval()
    metrics = []

    with torch.no_grad():
        for inputs, y_batch in data_loader:
            inputs = {name: X.to(device) for name, X in inputs.items()}
            y_batch = y_batch.to(device)

            y_pred = model(**inputs)
            metric = metric_fn(y_pred, y_batch)
            metrics.append(metric)

    return aggregate_fn(torch.stack(metrics))

In [157]:
evaluate(
    model=model,
    data_loader=valid_loader,
    metric_fn=criterion
)

tensor(0.4412)

In [161]:
#Building Models with Multiple Outputs
class WideAndDeep4(nn.Module):
  def __init__(self, n_wide_features, n_deep_features):
    super().__init__()
    self.deep_stack= nn.Sequential(
        nn.Linear(n_deep_features, 50),
        nn.ReLU(),
        nn.Linear(50, 40),
        nn.ReLU()
    )
    self.output_layer= nn.Linear(40 + n_wide_features, 1)
    self.aux_output_layer= nn.Linear(40 , 1)

  def forward(self,X_wide, X_deep):
    deep_output=self.deep_stack(X_deep)
    wide_and_deep=torch.concat([X_wide,deep_output], dim=1)
    main_output=self.output_layer(wide_and_deep)
    aux_output=self.aux_output_layer(deep_output)
    return main_output, aux_output

In [162]:
torch.manual_seed(42)
model=WideAndDeep4(
    n_wide_features=X_train[:, :5].shape[1],
    n_deep_features=X_train[:, 2:].shape[1]
)
model=model.to(device)

In [163]:
optimizer=torch.optim.SGD(model.parameters(), lr=learning_rate)

In [164]:
def train(model, optimizer, criterion, data_loader, n_epochs):
    model.train()

    for epoch in range(n_epochs):
        total_loss = 0.0

        for inputs, y_batch in data_loader:
            inputs = {name: X.to(device) for name, X in inputs.items()}
            y_batch = y_batch.to(device)

            optimizer.zero_grad()

            y_pred, y_pred_aux = model(**inputs)

            main_loss = criterion(y_pred, y_batch)
            aux_loss = criterion(y_pred_aux, y_batch)

            loss = 0.8 * main_loss + 0.2 * aux_loss

            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        mean_loss = total_loss / len(data_loader)
        print(f"epoch {epoch + 1}/{n_epochs}, loss {mean_loss:.4f}")

In [166]:
train(
    model=model,
    optimizer=optimizer,
    criterion=criterion,
    data_loader=train_loader,
    n_epochs=20
)

epoch 1/20, loss 1.7901
epoch 2/20, loss 0.7735
epoch 3/20, loss 0.6958
epoch 4/20, loss 0.6514
epoch 5/20, loss 0.6174
epoch 6/20, loss 0.5904
epoch 7/20, loss 0.5681
epoch 8/20, loss 0.5498
epoch 9/20, loss 0.5341
epoch 10/20, loss 0.5215
epoch 11/20, loss 0.5100
epoch 12/20, loss 0.5004
epoch 13/20, loss 0.4920
epoch 14/20, loss 0.4840
epoch 15/20, loss 0.4777
epoch 16/20, loss 0.4721
epoch 17/20, loss 0.4679
epoch 18/20, loss 0.4632
epoch 19/20, loss 0.4599
epoch 20/20, loss 0.4570


In [167]:
def evaluate(model, data_loader, metric_fn, aggregate_fn=torch.mean):
    model.eval()
    metrics = []

    with torch.no_grad():
        for inputs, y_batch in data_loader:
            inputs = {name: X.to(device) for name, X in inputs.items()}
            y_batch = y_batch.to(device)

            y_pred, _ = model(**inputs)
            metric = metric_fn(y_pred, y_batch)
            metrics.append(metric)

    return aggregate_fn(torch.stack(metrics))

In [168]:
evaluate(
    model=model,
    data_loader=valid_loader,
    metric_fn=criterion
)

tensor(0.4458)